#!/bin/csh

setenv EPICS_APP_2BMTS /home/beams/USER2BMB/epics/synApps/support/tomoscan/
setenv EPICS_APP_2BMB /net/s2dserv/xorApps/epics/synApps_5_8/ioc/2bmb
setenv EPICS_APP_SPINNAKER /APSshare/epics/synApps_6_3/support/areaDetector-R3-14/ADSpinnaker
setenv EPICS_APP_GENICAM /APSshare/epics/synApps_6_3/support/areaDetector-R3-14/ADGenICam
setenv EPICS_APP_AD /APSshare/epics/synApps_6_3/support/areaDetector-R3-14/ADCore

set output = `perl $EPICS_APP_2BMB/release.pl $EPICS_APP_2BMB`
$output

#####################
# prepare MEDM path
#
if (! ${?EPICS_DISPLAY_PATH}) setenv EPICS_DISPLAY_PATH '.'
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_APP_SPINNAKER/spinnakerApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_APP_GENICAM/GenICamApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_APP_AD/ADApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$SUPPORT/all_adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_APP_2BMTS/tomoScanApp/op/adl

medm -x -macro "P=2bm:,R=MCTOptics:,ER=Energy:,EPS=2bm:,FE=2bma:,Q1=A_shutter:,Q2=B_shutter:,P1=2bmb:,AD=2bmSP2:,AD_CAM=cam1:,AD_PROC1=Proc1:,AD_HDF=HDF1:,AD_MODEL=PGR_GS3_U3_23S6M,TS=2bmb:,TS_R=TomoScanStream:,TS_BEAMLINE=tomoScan_2BM,M1=m63,M2=m57,M3=m100,M8=m54,M10=m1,M11=m2,M12=m3,M13=m4,M14=m5,M15=m7,M16=m8,AERO=2bmbAERO:,AERO_M1=m1,P2=2bmS1:,M5=m2,M6=m1,T=table3,Q=Table3" ../../mctOpticsApp/op/adl/mct_main.adl &