#!/bin/csh
setenv DSERV_DIR       /net/s32dserv/xorApps/epics
setenv EPICS_TS        /local/usertxm/epics/synApps/support/tomoscan/
setenv EPICS_TXMO      /local/usertxm/epics/synApps/support/mctoptics/
setenv EPICS_APP       $DSERV_DIR/screens/32idsectorApp
setenv EPICS_APP_A     $DSERV_DIR/synApps_6_0/ioc/32ida
setenv EPICS_APP_C_TXM $DSERV_DIR/synApps_6_0/ioc/32idcTXM

set output = `perl $EPICS_APP_A/release.pl $EPICS_APP`
$output

#####################
# prepare MEDM path
#
if (! ${?EPICS_DISPLAY_PATH}) setenv EPICS_DISPLAY_PATH '.'
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_APP/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_APP_A/32idaApp/op/adl

setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_2_1/ioc/32idaKMT/32idaKMTApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_6_0/ioc/32idb/32idbApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_6_0/ioc/32idc01/32idc01App/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_6_0/ioc/32idc02/32idc02App/op/adl

#setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_APP_C_TXM/32idcTXMApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_TS/tomoScanApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$EPICS_TXMO/mctOpticsApp/op/adl

setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_8/ioc/32idbPLC/32idbPLCApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_8/ioc/32idcPLC/32idcPLCApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_8/ioc/32idbEXP/32idbEXPApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_8/ioc/32idcEXP/32idcEXPApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_8/ioc/32idcTMP/32idcTMPApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_7/ioc/32idSOFT/32idSOFTApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_7/ioc/32idcSOFT/32idcSOFTApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_8/ioc/32idbAMCI/32idbAMCIApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DSERV_DIR/synApps_5_8/ioc/32idbJOSH/32idbJOSHApp/op/adl

setenv EPICS_DISPLAY_PATH $STD/stdApp/op/adl':'$EPICS_DISPLAY_PATH

setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$ASYN/opi/medm
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$AUTOSAVE/asApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$CALC/calcApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$CAPUTRECORDER/caputRecorderApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$CAMAC/camacApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DAC128V/dac128VApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DELAYGEN/delaygenApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$DXP/dxpApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$IP/ipApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$IP330/ip330App/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$IPUNIDIG/ipUnidigApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$LOVE/loveApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$MCA/mcaApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$MOTOR/motorApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$OPTICS/opticsApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$QUADEM/quadEMApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$SSCAN/sscanApp/op/adl
set SOFTGLUE=${SUPPORT}/softGlue-R2-8
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$SOFTGLUE/softGlueApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$VME/vmeApp/op/adl
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'$ASYN/medm

# Add "all_adl" until ebrick support module is added to synApps.
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/APSshare/epics/synApps_5_2_1/support/ebrick/2-0-3/op/adl

# Add measComp until iocs are upgraded to synApps_5_7
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/APSshare/epics/synApps_5_7/support/measComp-1-0/measCompApp/op/adl

# add USAXS screens
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/home/beams/S32USAXS/medm/usaxs
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/home/beams/S32USAXS/medm/brq
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/home/beams/S32USAXS/medm/mir01
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/home/beams/S32USAXS/medm/uni

# add undulator screens
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/APSshare/adlsys/sr/id
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/APSshare/adlsys/site

# add Andor area detector medm (fdc 4/14/13)
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/home/beams/USR32IDC/areaDetector/TXM_NEO/all_adl

# add Photron (w/ ADCore-2-4) adls
setenv EPICS_DISPLAY_PATH $EPICS_DISPLAY_PATH':'/home/beams/USR32IDC/areaDetector/Photron

#cd $EPICS_APP_C_TXM/32idcTXMApp/op/adl
medm -attach -x -dg +50+50 -macro "P=32idcTXM:, P0=32id:, R0=TomoScanStep:, B0=tomoScanStep_32ID, P1=32id:, R1=TomoScan:, B1=tomoScan_32ID, P2=32idb:, BL=32ID, P4=32ida:, SK=32idcMC:, PG=32ARV1:, R=cam1:, R2=Proc1:, P5=32id:, R5=MCTOptics:, P6=32id:, P7=32idcEXP:, P8=32idcUC8:, R6=TomoScanStream:, B6=tomoScanStream_32ID, RO=obj, PID1=fb4, TITLE1=Horizontal, PID2=fb3, TITLE2=Vertical, VALVES_PLC=32idcPLC:, CRLRelays=32idbPLC:, Contr2=xps:c1:, Contr5=nf:c0:, Contr6=ens:c1:, Contr7=nf:c0:, Contr8=mxv:c1:, Contr12=mcs:c2:, Contr13=mcs:c3:, P3=32idcTXM:, Contr14=mcs:c0:, S=uniblitz:" -local ../../mctOpticsApp/op/adl/txm_main.adl &



